### ISSUE TITLE
AA wireless looses connection and reboots

### ISSUE THREAD

**Issue by Letalis** [cpebit/aawireless-issues#116]
**Describe the bug**
The unit starts normally but after x amount of time it stops working and i can see that it blink blue and green before it's up and running again.

**Screenshots**
N/a

**Car (please complete the following information):**
 Hyundai ioniq 5

**Headunit (please complete the following information):**
 - built in

**Smartphone (please complete the following information):**
 - Device: OnePlus 8pro
 - Android version 12

**Additional context**
It takes about 5-10 second before it's up again.

**Comment by baltek71** [comment]
The same issue observed several times (firmware 2.0.0)

**Car (please complete the following information):**
Kia Stinger

**Headunit (please complete the following information):**

built in

**Smartphone (please complete the following information):**

Device: Samsung Galaxy Note 20 Ultra
Android version 12

**Comment by Snirpo** [comment]
Please try:

- Set wifi channel to 149
- Enable passthrough

**Comment by Letalis** [comment]
Hi Snirpo,

I did that but had one short trip and a reboot. Will try more tomorrow and see if it's still present.
Is there any debug mode to help you out.

**Comment by Snirpo** [comment]
Yes, you can enable debug mode and shoot in a bug report from help and support in the app. Not sure if it's much help in this case, but who knows.

**Comment by PanoSpent** [comment]
I have the same issue on my alfa romeo mito and [ATOTO head unit](https://www.myatoto.com/index.php?m=content&c=index&a=show&catid=15&id=65). I will try to do what you mentioned on the last comment. I received the unit one or two weeks ago.

**Comment by PanoSpent** [comment]
Hi again,

I sent a bug report as you requested @Snirpo .

**Comment by Snirpo** [comment]
@Janz25 can you share your device id? So I can check which alpha version you were on before.

**Comment by Janz25** [comment]
Thank you @Snirpo, my aaw id: BpboTrw4

**Comment by Snirpo** [comment]
@Janz25 I enabled the latest develop firmware for you. Can you check if this firmware makes non-passthrough work ok again?

**Comment by PanoSpent** [comment]
hey @Snirpo any update on our comments? It is not nice to have this bug everytime you go for a ride. Sometimes you lose your route because of the disconnections.

**Comment by Snirpo** [comment]
@PanoSpent does the same thing happen in passthrough mode on your HU?

**Comment by PanoSpent** [comment]
I havent checked if it happens in passthrough mode. I will check it today. My device id is YC7ePUXC if you want to see the debug report i sent. I will check the passthrough mode today and i will let you know what happened. Does the passthrough mode limits the functionality of the device or something?

**Comment by Janz25** [comment]
> @Janz25 I enabled the latest develop firmware for you. Can you check if this firmware makes non-passthrough work ok again?

Thanks @Snirpo , just noticed my device reverted to the previous alpha firmware. I have deactivated the passtrough mode and will monitor again. Will let u know if i encounter any connection issue again.

**Comment by PanoSpent** [comment]
@Snirpo the same issue ensists even on passthrough mode.

**Comment by Snirpo** [comment]
I'm splitting up this issue, cause they are most likely not the same issue. On Hyundai/Kia there's an issue with non-passthrough mode. According to multiple records, passthrough mode makes the connection stable. If this is not the case for you please tell.

**Comment by Snirpo** [comment]
@Janz25 It seems you reverted to 2.0.1, not sure why this happened, but please update to the latest develop firmware, it should be enabled.

**Comment by Snirpo** [comment]
@PanoSpent Let's continue in #133

**Comment by Snirpo** [comment]
Same thing happens on EV6, bassiccly same car as the Ioniq 5:

[Malte (Kia EV6, Gen5W Nav, Sony Xperia 5)
I am still evaluating. Passthrough has been perfectly reliable, while normal mode gives disconnects. Head unit gives "phone is not responding". I am using Hotspot mode to rule out issues with my wifi

**Comment by Janz25** [comment]
> @Janz25 It seems you reverted to 2.0.1, not sure why this happened, but please update to the latest develop firmware, it should be enabled.

Ok, i will update the firmware as below screenshot which i assume its the latest development firmware that u enabled for me. 

Btw, today morning its disconnected again despite im on previous firmware 2.0.1. I did sent the bug report with my aaw id as the title if u want to have look the bug report.


![Screenshot_20220605-223558_AAWireless](https://user-images.githubusercontent.com/106788673/172055854-6ed1e071-e4e2-4f5d-8be5-d33d4fcf5383.jpg)

**Comment by Letalis** [comment]
I have tried using pasthrough since you asked about it, @Snirpo .
And that worked much better.
And yesterday I turned it off again to test att the connection issues multiplied.

**Comment by skanadian** [comment]
I'm observing the same in my 21 Stinger. Works fine in passthrough mode, random disconnects in normal/dongle.  Latest FW on AAwireless and my Gen5 HU.

I have root and I'm very apt in linux/android if you guys need help troubleshooting.

**Comment by Snirpo** [comment]
Thanks! We are deep diving in this issue. Haven't found the exact cause yet. We'll keep this ticket up to date if we have found the cause. @skanadian Can you possibly turn on debug mode on the device via help and support --> bug report and shoot in a bug report when it happens.

**Comment by Letalis** [comment]
I sent a debug the other day (i think)

**Comment by skanadian** [comment]
Just sent.  Device ID pI2kf12W
It was on 2.4ghz, I'll send another on 5ghz tonight if it triggers.   I've tried every wifi channel under the sun but I understand ruling it out.

**Comment by Snirpo** [comment]
@skanadian Well the main thing I need to know if it's stable in passthrough mode.

**Comment by skanadian** [comment]
@Snirpo I don't mind at all.  Feel free to push me the firmware and I'll test tonight.

**Comment by Snirpo** [comment]
@skanadian you're back on 1.12

**Comment by skanadian** [comment]
@Snirpo sent 2 reports from 1.12 last night.  Both times rapid disconnect/reconnect, but doesn't seem to recover from it like 2.x does. 

I switched to passthrough after those reports and it was solid the 2hrs I drove after that.

Let me know if you need any more troubleshooting.  Again, I'm very good from the command line.  Any hints at the issue?

**Comment by Snirpo** [comment]
I bought an Alpine ilx905 (has the same issue) to reproduce this issue. And I have been able the reproduce it. Now only to figure out why. Getting there.

Someone on our Slack channel with an EV6 actually just confirmed the same thing. The same thing happens in 1.12.0, which to me is quite surprising. Because it seemed like these issues only started on 2.0.

**Comment by Letalis** [comment]
Can I assist more from my side?

**Comment by Snirpo** [comment]
We got confirmation this issue happens all the way back down to firmware 1.8. I've just pushed a version of the app where we enable passthrough mode by default for new devices as a quick fix.

I have been only looking at changes from firmware 2.0, but now we know it's not a specific 2.0 issue. This problem has probably been in there since 1.0, but never triggered before.

I'm pretty sure it's something related to SSL, so I'll focus on that.

**Comment by Janz25** [comment]
Hi @Snirpo , im still experiencing mutiple disconnection within the same trip. My app and firmware always updated to the latest beta. Can help to check.

**Comment by Snirpo** [comment]
@Janz25 in passthrough mode?

**Comment by Janz25** [comment]
In normal mode. I believed it should be okay with passthru mode, but i cant fully utilized the aaw function.

**Comment by Janz25** [comment]
Ok sure, do let me know if u need me to do anything here, meanwhile will keep my firmware and app updated whenever available. Thanks @Snirpo

**Comment by Snirpo** [comment]
We figured it out. I'll be merging the changes to develop this evening and we will be releasing 2.0.2 as a hotfix.

**Comment by maisondasilva** [comment]
> We figured it out. I'll be merging the changes to develop this evening and we will be releasing 2.0.2 hotfix.
> 
> @Janz25 @Letalis @skanadian can you verify if the latest develop firmware fixes the issue?

Is this fix a final release?  When should it be released to the public?  Can I get it on my Aa?

**Comment by Snirpo** [comment]
This fix is already in the dev firmware. We will also push this this fix in the 2.0.x branch as 2.0.2 as mentioned in https://github.com/cpebit/aawireless-issues/blob/master/FIRMWARE-CHANGELOG.md

**Comment by maisondasilva** [comment]
> This fix is already in the dev firmware. We will also push this this fix in the 2.0.x branch as 2.0.2 as mentioned in https://github.com/cpebit/aawireless-issues/blob/master/FIRMWARE-CHANGELOG.md

Until tomorrow should it be out for beta or not if it can't be released for my AA?

**Comment by Janz25** [comment]
@Snirpo , received an update, believed this the development firmware that you mentioned. Had it installed this morning and will revert back. Thanks

![Screenshot_20220620-085312_AAWireless](https://user-images.githubusercontent.com/106788673/174519511-26bac142-f15c-4e98-b87b-a37a546f8b32.jpg)

**Comment by skanadian** [comment]
I'm still stuck on 1.12.  Can you push dev to my device and I'll test?  My ID is up above.  Thanks.

**Comment by Snirpo** [comment]
@skanadian You're back on production firmware now (2.0.2) which also contains this fix.

**Comment by maisondasilva** [comment]
I updated mine here in the beta app. I received the translated version @Snirpo Thanks

**Comment by skanadian** [comment]
@Snirpo Thank you.  Drove for a little over an hour.  Not a single hiccup.  No lags, no disconnects, nothing, it was perfect.  Changed a few settings (ie. DPI) to test my use case, no issues.

Amazing job! I really appreciate this and your product in general.

If you could remove my device from any custom firmware lists so I can get retail firmware in the future that would be great.   Again, thank you!

**Comment by Ghasemjb** [comment]
> @Snirpo , received an update, believed this the development firmware that you mentioned. Had it installed this morning and will revert back. Thanks
> 
> ![Screenshot_20220620-085312_AAWireless](https://user-images.githubusercontent.com/106788673/174519511-26bac142-f15c-4e98-b87b-a37a546f8b32.jpg)

Hi, how can I receive the latest 2.1.0 please? 

Regards

**Comment by Ghasemjb** [comment]
> Please try:
> 
> * Set wifi channel to 149
> * Enable passthrough

Hi , how can I receive the latest 2.1.0 software please? 
Thank you for your great work.

**Comment by ultraboost** [comment]
I too have been having random disconnects from AA on a Porsche PCM4. Whatever setting or WiFi channel, including passthrough 'enabled' I tried the headunit closed AA after 5 minutes or so. Even tried swapping the original AA wireless unit for the latest one. It happened with firmware v1.8, 2.0 and 2.01. Older firmware was stable. I've updated to v2.02 this evening so hopefully that will resolve it.

**Comment by Snirpo** [comment]
I'm closing this issue. This specific issue has been fixed in 2.0.2. 

@ultraboost Your issue is unrelated to this issue when it's also unstable in passthrough mode. I'm creating a separate issue for it.
