### ISSUE TITLE
UConnect only works a few times, then needs to be re-added

### ISSUE THREAD

**Issue by luvwot** [cpebit/aawireless-issues#128]
**Describe the bug**
It seems that once I get AAWireless to work, it only works for 1-2 trips/connections. After that, the next time it tries to connect I see the unit boot, then the LED flashes blue for a little while like it's trying to connect, then the LED goes solid white. If the USB port was still powered (1 hour delay after the ignition turns off), the LED starts solid white, then flashes blue, then goes solid white again. In either case, AAWireless doesn't work.

I did identify a work-around so I don't have to completely setup from scratch each time. In the UConnect screen, I go to paired devices and make it forget the AAWireless device that's been discovered for Android Auto. Then (also on the UConnect unit) I disconnect my phone, wait a few seconds, then reconnect the phone. After about 15-20 seconds AAWireless comes up just fine.

When I disconnect and reconnect from the phone without forgetting the AAWireless device in the headunit, the AAW blinks blue for about 10 seconds then goes back to solid white. Similarly, when I just disconnect and reconnect from the headunit it will blink blue then go back to solid white. The only way I've been able to get it to work is to have the headunit forget AAW, then disconnect and reconnect from either the headunit or the phone.

**Device name (AAWireless/AndroidAuto-AAWxxxxxxx) (please complete the following information):**
AAWireless AAWHu0f11f0
Firmware 2.0.1
App 2.14.0

**Car (please complete the following information):**
Dodge Durango

**Headunit (please complete the following information):**
Dodge UConnect 8.4 (2018 model)

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S22
 - Android 12

**Additional context**
Since the USB port on the vehicle remains powered for 1 hour, I have to use start/stop mode.  I've tried:

- Passthrough enabled and disabled
- Dongle mode enabled and disabled
- USB mode Default, MTP, MTP with restart, MTP with retry

Bug report was submitted May 28, 2022.  Associated posts in xda-developers:
https://forum.xda-developers.com/t/aawireless-general-discussion-and-support.4247677/page-175#post-86948319
https://forum.xda-developers.com/t/aawireless-general-discussion-and-support.4247677/page-176#post-86951789
https://forum.xda-developers.com/t/aawireless-general-discussion-and-support.4247677/page-176#post-86955081

It sounds like this is very similar to https://github.com/cpebit/aawireless-issues/issues/22

This problem does not exist in 1.8.

**Comment by Snirpo** [comment]
#22 seems indeed the exact same issue. Not sure why it was closed back then. Apparently is was fixed, and somehow it's now broken again in 2.x. Haven't found the exact reason yet.

**Comment by luvwot** [comment]
Downloaded the beta app but it still shows firmware 2.0.1 as the latest for me. I did check the ID and it seems correct.

**Comment by Snirpo** [comment]
@luvwot should be enabled now.

**Comment by luvwot** [comment]
@Snirpo I just checked for firmware updates again and still see 2.0.1.
![Screenshot_20220603-090033_AAWireless](https://user-images.githubusercontent.com/106754153/171903363-c1c3fcae-e0ff-459a-bdd7-3093d70dbefd.jpg)

![Screenshot_20220603-090042_AAWireless](https://user-images.githubusercontent.com/106754153/171903367-e9a3b6c8-f046-4cd9-b564-af806189dbf2.jpg)

**Comment by Snirpo** [comment]
For reference, devices with the same issue:

AAWireless-282Cm5iE
AndroidAuto-AAWiknizR0o
AAWireless-1ntmMMEV
aPOzac3c
AAWMQunVMrk

**Comment by luvwot** [comment]
I was able to download 2.1 earlier today and took a series of short trips this afternoon.  AAW connected every time (which is the first time it's ever managed to do this)!

I did have 2 occasions where AAW disconnected.  One time it reconnected on its own after about 15 seconds; the other time it failed to reconnect even after I unplugged the AAW unit and plugged it back in.  After getting shutting off the car, the next time I got in it reconnected just fine.

Verdict at this point is that 2.1 with "Stop/start: Device USB controlled" is working!  I'll keep an eye out and update this over the weekend as I take a few more trips.  None of my stops today was less than an hour so the AAW device was powered the whole time.

**Comment by Snirpo** [comment]
@luvwot sounds good. Can you possibly shoot in a bug report? So I can check how it's working right now. You can start debug mode and immediately stop it, then push the report.

**Comment by luvwot** [comment]
@Snirpo I just generated the report.  This morning AAW did correctly connect on the first attempt.

FYI - Last night I made a couple more short trips and AAW failed to connect on both of them.  LED started green (booting), then went white; unfortunately I didn't notice if was blinking blue before going white.  Disconnecting the phone at the headunit and reconnecting did not trigger a reconnect.  On both of these trips, the car was off just long enough for the USB port to shut off (no power).  Weird that this morning after being off power for many hours it connected just fine.

**Comment by Snirpo** [comment]
Yeah I seems the car does not like multiple sessions without unplugging. Are you ok with downgrading to 1.8/1.12 and running a debug session? I'm not really sure what the difference is. We didn't really modify anything regarding USB in 2.x, so it must be some sideeffect of something else.

**Comment by luvwot** [comment]
Yes, absolutely fine with testing that out.

**Comment by Snirpo** [comment]
Ok, 1.8 should be available now. According to multiple reports, 1.8 should work fine. Please keep debug mode running for a while and send in the report after a few trips :) Thanks!

For my own reference: 4A:30:43:81:D3:2F

**Comment by luvwot** [comment]
And is 1.12 the mobile app version I need to run?  If so, where do I get that?

**Comment by Snirpo** [comment]
Oh no sorry, you can keep using the app version you have now.

**Comment by Snirpo** [comment]
@luvwot was wondering if you already tried 1.8?

**Comment by Snirpo** [comment]
The logs are a bit confusing with all these wifi disconnects, but not sure if that's the source of the issue. Can you possibly shoot in a bug report on version 1.8? So I can compare the logs versus 1.8.

**Comment by jimbotron123** [comment]
I have two devices, one of which was sent to me as a replacement for the first one as I've been having these issues on and off for so long. I was able to get one of the devices (the older one) downgraded to 1.8, but the other one is stuck on 1.12.0 from the factory.

AAWireless-282Cm5iE - stuck on 1.12.0 - new from factory
AndroidAuto-AAWiknizR0o - original unit that had current 2.x firmware, constant issues, dropped to 1.8. Far less issues with disconnect (but they still do exist), unit will usually not auto-launch AAW until I open the AAWireless app and click on "device settings", then it quickly connects and we're on our way.

Vehicle is a 2020 Ram with Uconnect 12" screen. 

Please let me know if I can test/help in any way.

**Comment by Snirpo** [comment]
@jimbotron123 Doesn't sound like completely the same issue. 

Disconnection issues are mostly created by interference / faulty hardware. I see you already tried channel 149, and I see it's a batch 2 device, so it's possibly a hardware defect. Did you already try the new device? It's a gen 2 one, so the first version of the firmware is 1.12.0 for that one.

Auto launch issues sound like issues with start/stop, which I see you are using. This is likely a phone side/companion app issue. The LED is most likely white when this happens?

**Comment by Snirpo** [comment]
@luvwot 

This is not the source of the issue, but the log is cluttered with:

`2020-09-20T11:07:22.963714+00:00 localhost kernel: [ 1405.675171] wl_notify_connect_status_ap: event WLC_E_DEAUTH(5) status 0 reason 7
2020-09-20T11:07:22.963816+00:00 localhost kernel: [ 1405.675224] wl_notify_connect_status_ap: deauthenticated device ca:8d:1e:05:b5:9a
2020-09-20T11:07:22.964398+00:00 localhost hostapd: wlan0: STA ca:8d:1e:05:b5:9a IEEE 802.11: disassociated
2020-09-20T11:07:42.963688+00:00 localhost kernel: [ 1425.675778] wl_notify_connect_status_ap: event WLC_E_DEAUTH(5) status 0 reason 7
2020-09-20T11:07:42.963788+00:00 localhost kernel: [ 1425.675829] wl_notify_connect_status_ap: deauthenticated device ca:8d:1e:05:b5:9a
2020-09-20T11:07:42.965140+00:00 localhost hostapd: wlan0: STA ca:8d:1e:05:b5:9a IEEE 802.11: disassociated
2020-09-20T11:08:02.963667+00:00 localhost kernel: [ 1445.676415] wl_notify_connect_status_ap: event WLC_E_DEAUTH(5) status 0 reason 7
2020-09-20T11:08:02.963764+00:00 localhost kernel: [ 1445.676467] wl_notify_connect_status_ap: deauthenticated device ca:8d:1e:05:b5:9a
2020-09-20T11:08:02.966095+00:00 localhost hostapd: wlan0: STA ca:8d:1e:05:b5:9a IEEE 802.11: disassociated`

This is not the phone. Do you have a laptop or another device connected to the hotspot of the device?

**Comment by luvwot** [comment]
@Snirpo 
ca:8d:1e:05:b5:9a is the mac address of the phone (Samsung Galaxy S22).  The phone's hotspot is not activated, nor is the headunit's.

**Comment by luvwot** [comment]
@Snirpo 
I'll download 1.12.0.  Probably not a lot of opportunity to test it on actual trips today but hopefully at least 1 or 2 in the next couple days.

**Comment by Snirpo** [comment]
@luvwot Thanks, in the meantime I'll dig further. It's a really odd one, I have no real explanation at this point.

**Comment by luvwot** [comment]
I've been on 1.12.0 for several days now.  Multiple trips with short pauses (USB stays powered on) and long pauses (USB powers off).  So far I haven't had any failures to connect.  The only hiccup was a drop-out/reset, but I think that was due to me bumping the USB cable so I've rerouted the cable to get it out of the way and no problems since then.

@Snirpo If it's helpful, I can generate a log next time I'm not at home so we're not starting out with my phone connected to my home Wi-Fi, or I can generate a log from home so it's more similar to what I've generated in the past.

**Comment by Snirpo** [comment]
@XDA - Aberk 

I am still getting the no device supported error with no recovery but to forget aawireless in the HU and unplug/replug the aawireless device, but I think I have it narrowed down to a particular scenario.

If I shut the vehicle off and the HU powers down, but the USB port keeps power to the aawireless device and I walk far enough away that the phone and aawireless device lose connectivity then come back to the vehicle and key on like normal I get the no supported device error.

If I am gone from the vechicle long enough that the USB port powers down, I have no issues when I come back.

If I turn the vehicle off and the aawireless device still has power and I am only a few feet away {like when getting fuel), I have no issues when returning to the vehicle.

@luvwot Can you confirm above? Because then we probably have narrowed it down :)

**Comment by luvwot** [comment]
@Snirpo I saw that, too, and went out to check it.  It wasn't clear to me from Aberk's post whether the "device not supported" message is preventing normal operation or not.

In my case, pretty much every time I connect, I get the "device not supported" message (even if just for a moment).  I'm pretty sure I've seen this occasionally even on a wired connection, but I can't be sure at this point.

Regardless, with 1.12.0 I'm connecting every time, regardless of that message. Reconnections are good with USB remaining powered whether I remain in range or temporarily go out of range, or if everything powers down before I try to reconnect.

I was trying to aggregate all of the Uconnect posts in xda to see if there are commonalities in the headunits.  It seems like the ones with the 8.4" screens (series UAQ and UCQ) have better luck with 1.8/1.12, while those with the newer 12" screens (series UAX) are having better luck with the latest firmware.  I haven't confirmed that's the case since some of the posts don't indicate exactly which Uconnect they have.

**Comment by Snirpo** [comment]
I'm pretty sure the issue is related to how 2.x vs 1.8 work when the USB port is still powered. @luvwot I enabled the latest dev firmware for you, can you please try the device in MTP USB mode?

**Comment by Snirpo** [comment]
We have narrowed down the issue. When the HU side kills the USB connection because of not receiving responses for a while, it gets Uconnect into a bad state. Same thing actually also happens on Pioneer head units. When the AAWireless side kills the USB connection, it's fine. This is what happened pre < 2.0.

We now have to think of a proper solution, because we rather keep the new logic (without breaking Uconnect). We don't really fancy adding yet another setting a la VAG fix. Will keep you up to date.

**Comment by luvwot** [comment]
@Snirpo I downloaded the dev firmware this morning.  I set USB to MTP with retry.
A few tests sitting in my garage all looked like it reconnected each time.  I'll be able to run a few better tests later today after I make some real trips with various delays and USB power states.

**Comment by Snirpo** [comment]
@luvwot Can you try the plain MTP mode, without retry?

**Comment by luvwot** [comment]
@Snirpo OK, just changed mode to plain MTP.  Tests in the garage seem OK.  I'll try to run a couple more tests after the USB powers down to see if it reconnects that way, too.

**Comment by luvwot** [comment]
@Snirpo I also just got a new app download from Firebase so I have that loaded on my phone, too.
AAWireless 2.15.0-202206121834-develop-33e7e78 (2150000)

Just so we don't find out later that I have incorrect settings, here's what I have right now.
USB: MTP
Passthrough: disabled
WiFi Settings: (Country US, Hotspot, 5GHz, channel auto)
Start/Stop: enabled (the 2 experimental options are off)
WiFi Connect Timeout: 20000
VAG crash fix: disabled
Change DPI: 0
Remove tap restriction: disabled
Disable media sink: disabled
Disable TTS sink: disabled
Auto video focus: disabled
Dongle mode: disabled
Developer mode: disabled

**Comment by Snirpo** [comment]
@luvwot seems fine! :)

**Comment by luvwot** [comment]
@Snirpo I let the 1 hour Uconnect power timeout expire, USB shuts off and AAW loses power as expected.
Turned the car on, I see AAW boot solid green), wait (solid white), then starts blinking blue but never connects.
My phone's notifications indicate:
Android Auto: connected to your car
AAWireless-Hu0f11f0: Connected to device

I generated a bug report a couple minutes ago.

**Comment by Snirpo** [comment]
@luvwot with retry this does not happen?

**Comment by luvwot** [comment]
@Snirpo That's correct.  I also just downloaded the latest app from Firebase and got the latest firmware.  I re-tested MTP and I consistently get a successful first connection, but later attempts to connect fail with a blue blinking LED.  With MTP with retry, I seem to get a reliable first connection and reliable subsequent connections. 

Note - Since I just did the downloads I need to do additional testing later after the USB powers down.

**Comment by Snirpo** [comment]
@luvwot thanks, MTP with retry seems a reasonable workaround. Will also work in the current firmware.

**Comment by luvwot** [comment]
@Snirpo Unfortunately, this latest combination of builds does not give me good connections long term.  After the USB powered down, on my next attempt I got the blinking blue light upon attempting to connect. I did my standard "forget device" on the HU and it did connect correctly twice.  Third time failed with the blinking blue light again.

This firmware build is 202206121836-develop-6d8dd10-develop-3d09df80
Device is set for MTP with retry.

**Comment by Snirpo** [comment]
Small update. We are comparing AAWireless to the MA1. Found a difference how the MA1 disconnects from USB vs AAWireless.

On firmware 1.x the disconnection process was different. That's why 1.x works, and 2.x doesn't. We don't really want to go back the the 1.x logic though, because it only works probably in non-passthrough mode.

To be continued.

**Comment by Snirpo** [comment]
OK basically there's no magic involved on the MA1, it only disconnects from USB a bit earlier. The problem on my Pioneer HU here on my desk, and possibly also Uconnect is the car disconnecting the USB connection earlier than the device, then the HU gets into a bad state where the device is still "connected" while it's actually not.

I lowered some timeouts and made retrying default. @luvwot can you check if it better now in the latest develop firmware?

**Comment by luvwot** [comment]
@Snirpo Will do.  I've downloaded the firmware from today and the latest mobile app from Firebase.  I'll let you know how it works out after I've had a chance to test some long delays/drives.

**Comment by luvwot** [comment]
@Snirpo Unfortunately this combination of firmware and app doesn't work well for me. The symptom I'm seeing now is that the LED is white, not blinking blue (so it appears to not even try to connect?).  If I forget the AAW from the headunit, I can get it to reconnect but it only works once or twice, then I have to forget it again.  This is the same experience that I had in previous/released 2.x firmware.

I think the firmware from a few days ago was working better, but I didn't get a whole lot of testing with it.

**Comment by Snirpo** [comment]
Can you turn off the start/stop mechanism for a while to see how it works without. White LED means start/stop is not working properly

**Comment by luvwot** [comment]
@Snirpo I tried turning off start/stop and ran into a problem where bluetooth on the phone doesn't reconnect to the headunit if the USB (for AAW) hasn't powered off.  If the USB was off then when I start the car and everything powers up it's fine.

I did also notice that it takes a lot longer for my phone to disconnect from the AAW Wi-Fi with start/stop disabled.

I just downloaded today's firmware build and turned start/stop back on to see if I can get a set of settings that work well.

**Comment by luvwot** [comment]
@Snirpo The latest couple builds of firmware don't seem to be as reliable as previous builds (from, say, a week or two ago). Most often now I'm back to being able to get connected once or twice, maybe 3 times if I'm lucky.  After that, I see the blinking blue LED for about 10 seconds, then the LED goes white.  At this point I have to make the headunit forget AAW and re-connect.

I've tried multiple combinations of dongle mode and passthrough, as well as USB default and MTP with retry.

**Comment by Snirpo** [comment]
@luvwot I'll revert all changes we did regarding "stale connection" timeouts in a special branch and put your device on that branch.

**Comment by Snirpo** [comment]
I'm really wondering what the actual source of this issue is. I thought we had the reason, but apparently we don't, because the latest builds should make this situation better instead of worse.

@fg64 Can you possible verify one thing for me? When it stops connecting after a few times, can you switch to "direct accessory" mode and check if it starts up? This would confirm that the HU is getting stuck in the "AA already started" state.

**Comment by luvwot** [comment]
@Snirpo USB mode "direct" seems to give me a boot loop.  Green LED, then one blue blink, off, then green again and it starts over.

**Comment by Snirpo** [comment]
@luvwot yeah normally I expect that. But in the situation where the HU does not start up AA anymore, it might actually trigger it to start.

**Comment by fg64** [comment]
@Snirpo Just got bck into the truck.  AAWireless would not reconnect.  Unit had a steady white light.  Changed to USB direct.  No change, steady white light.

**Comment by fg64** [comment]
Update.  Went out with the truck and no connection, solid white light.  Turned the truck off for about 15 minutes.  Came back, started up and AAW came up.  I'll see how it goes tomorrow.

**Comment by Snirpo** [comment]
@fg64 do you have any of the start stop modes enabled?

**Comment by fg64** [comment]
I do have start/stop enabled.  I will disable and give it a try.  Will be heading out shortly.

**Comment by fg64** [comment]
@Snirpo Disabled start/stop. Would not connect using USB direct mode. Looked like AAW kept rebooting. Switched to MTP mode and reconnected. Made several short stops and AAW reconnected each time.  Will continue testing.

**Comment by fg64** [comment]
@Snirpo When I got into the truck today AAW would not connect.  Removed it from projection settings, rebooted AAW and it connected right away.  I knew I would be making a few stops so I enabled debug.  After the third stop no connection and bug report was sent.  AndroidAuto-AAW4703rFeJ.

**Comment by Snirpo** [comment]
I posted a comment on https://5thgenrams.com/community/threads/aawireless-review.31303/page-7 to get a bit more help. Apparently , according to @jimbotron, the MA1 does not seem to have this issue. Which is surprising to me, cause on 2.x it's works the same as the MA1.

@fg64 are you ok with going back to firmware 1.8 and checking if the same problem happens with "passthrough" enabled?

**Comment by fg64** [comment]
@Snirpo  Sure, I'll give it try.

**Comment by luvwot** [comment]
@Snirpo I'm happy to go back to 1.8 as well if you need an extra test.  Since I have played around with various settings recently, please also indicate what settings for USB, passthrough, and dongle mode you'd like tested.

**Comment by Snirpo** [comment]
@luvwot enabled 1.8 for you as well. Could you try everything default + passthrough enabled?

So:
USB mode: default
Start / stop: disabled
Passthrough: Enabled

I'm just curious if the same thing happens where it only works a few times and then needs a reset on the HU side.

**Comment by luvwot** [comment]
> @luvwot enabled 1.8 for you as well. Could you try everything default + passthrough enabled?
> 
> So: USB mode: default Start / stop: disabled Passthrough: Enabled
> 
> I'm just curious if the same thing happens where it only works a few times and then needs a reset on the HU side.

What about dongle mode?

**Comment by Snirpo** [comment]
Dongle mode can be kept on :)

**Comment by Snirpo** [comment]
Correction, 1.8 does not have dongle mode of course :)

**Comment by luvwot** [comment]
> Correction, 1.8 does not have dongle mode of course.

Yeah, I realized that when I did the downgrade to 1.8 and it wasn't available.  
Quick tests over the last couple hours seem to be good.  It's properly/automatically reconnected 7-8 times in a row now, both with the phone remaining in close proximity (like if I was just filling up at a gas station) and farther away (like running into a store for a few minutes).  I still have to have a few tests where the USB completely powers down to see how that affects things.

**Comment by Snirpo** [comment]
@luvwot According to our backend passthrough is disabled, can you enable this?

**Comment by Snirpo** [comment]
@luvwot Thanks, just enabled I see :) I'm expecting it to act the same as firmware 2.x now: "UConnect only works a few times, then needs to be re-added". Can you verify if this is indeed correct? Thanks!

**Comment by luvwot** [comment]
Spying on me?  :)

I just enabled it. I'll run a few tests and let you know.

**Comment by fg64** [comment]
So far, a couple of short stops but close to the vehicle and reconnected OK.  After 1 stop which I believe I was out of range for a period, returned to the truck and no connection.  I unplugged AAW, it rebooted and connected again without removing it from the Projection settings.

**Comment by luvwot** [comment]
> @luvwot Thanks, just enabled I see :) I'm expecting it to act the same as firmware 2.x now: "UConnect only works a few times, then needs to be re-added". Can you verify if my assumption is correct? Thanks!
> 
> 4A:30:43:81:D3:2F

Confirmed.  With passthrough enabled it alternates between blinking green (10 seconds) then blinking blue (10 seconds).  Whenever it switches from green to blue, the headunit shows a "device not supported" message; dismissing the message doesn't do anything.

**Comment by fg64** [comment]
@luvwot That happened to me as well when I first updated the firmware.  "device not supported" continuously came up on the screen.  I removed AAW from the projection settings, rebooted AAW and then it worked.

**Comment by Snirpo** [comment]
@luvwot Can you possibly switch to "MTP" USB mode and run it for a while? It should get rid of the "unsupported USB" message, but my assumption is it will act the same.

**Comment by Snirpo** [comment]
@luvwot to confirm. When the HU is in this state, replugging won't help right? You have to fully delete the device from the HU?

**Comment by fg64** [comment]
@Snirpo When it happened to me yesterday, all I did was unplug AAW and plug it back in.  For me AA came back up without removing it from projection settings.  I'll be heading out later and see it it happens again.

**Comment by Snirpo** [comment]
I'm wondering in which situation you actually need to delete the device from the HU. Possibly after the HU has fully powered down (after an hour or so)?

**Comment by fg64** [comment]
That is a possibility. When it happened yesterday I was out of the truck for less than 15 minutes.

**Comment by luvwot** [comment]
> @luvwot Can you possibly switch to "MTP" USB mode and run it for a while? It should get rid of the "device not supported" message, but my assumption is it will act the same.
Correct, switching to MTP (or MTP with retry) gets rid of the device not supported message, but AAW still does not connect.

> When the HU is in this state, replugging won't help right? You have to fully delete the device from the HU?
Correct.  Once I get into a failure mode, I have to have the HU forget the AAW device.

> I'm wondering in which situation you actually need to delete the device from the HU. Possibly after the HU has fully powered down (after an hour or so)?
I'll continue to test this case.

One other thing.  With start/top disabled, when I'm in range of the AAW device and it's powered up (for instance, after arriving at home) my phone keeps trying to connect to AAW: notification is constantly on "Looking for Android Auto" and every 30 seconds or so Android Auto connects.  All this time, my phone is connected to the AAW WiFi so I have to use mobile data.  And finally, my battery life drops very rapidly.  So at least in my case, running with start/stop disabled is not an option. (I'll continue running with start/stop disabled for testing.)

**Comment by Snirpo** [comment]
@luvwot Thanks for the info. Start / stop disabled is only for testing this specific situation indeed :)

**Comment by fg64** [comment]
Got into the truck today after it sat overnight, "device not supported" continuously popped up.  Hitting OK dismissed the message, and it popped up again in a few seconds.  Rebooting AAW had no effect.  Removed AAW from projection settings, rebooted and AA came up fine.  After the first stop, which was about 20 minutes away from the truck, got back in and AAW did not connect.  Unplugged/plugged in dongle, AA came up fine without removing from projection settings.  Next short stop, same, no connection, rebooted and fine.

**Comment by Snirpo** [comment]
> Got into the truck today after it sat overnight, "device not supported" continuously popped up. Hitting OK dismissed the message, and it popped up again in a few seconds. Rebooting AAW had no effect. Removed AAW from projection settings, rebooted and AA came up fine. After the first stop, which was about 20 minutes away from the truck, got back in and AAW did not connect. Unplugged/plugged in dongle, AA came up fine without removing from projection settings. Next short stop, same, no connection, rebooted and fine.

@luvwot Can you confirm same thing happens on your car?

**Comment by fg64** [comment]
@Snirpo Sure, no problem.

**Comment by Snirpo** [comment]
I'm also building a special version now to try some stuff out.

**Comment by luvwot** [comment]
> > Got into the truck today after it sat overnight, "device not supported" continuously popped up. Hitting OK dismissed the message, and it popped up again in a few seconds. Rebooting AAW had no effect. Removed AAW from projection settings, rebooted and AA came up fine. After the first stop, which was about 20 minutes away from the truck, got back in and AAW did not connect. Unplugged/plugged in dongle, AA came up fine without removing from projection settings. Next short stop, same, no connection, rebooted and fine.
> 
> @luvwot Can you confirm same thing happens on your car? So short stop (USB still powered), replug is enough. Longer stop (USB powered down), needs removal on HU side.
> 
> (Sorry for asking so much info, trying to narrow it down :) )

Unplug and replug does not seem to resolve the issue on mine.  I get alternating green blinking and blue blinking after unplug/replug.  In my experience, once I get a failure to connect, the only way I've been able to resolve it is to forget AAW at the HU.

I either get the "unsupported" message or not depending on USB mode, but the message itself doesn't seem to actually cause problems (it's just an annoyance but possibly an indicator of some problem).

**Comment by Snirpo** [comment]
@luvwot I enabled a special Uconnect firmware for your device, it's bassiccly develop, but with some low level USB changes.

**Comment by luvwot** [comment]
@Snirpo I updated to the custom firmware.  After letting the car sit for about 40 minutes (USB powered on), I tried to connect and got alternating blinking green/blinking blue again. Unplug and replug of AAW did not reconnect.

**Comment by Snirpo** [comment]
@luvwot Are you sure it updated? I still see current version as 1.8.0 in the backend for some reason.

**Comment by luvwot** [comment]
> @luvwot Are you sure it updated? I still see current version as 1.8.0 in the backend for some reason.

It seems the update is failing to apply. After reaching 100% and waiting for reboot in the app, I see the AAW LED briefly turn green 5 times, then it completes a reboot (and the LED is red for a few seconds before looking like normal operation).  At this point it's still running the old firmware and the app confirms this.

I just tried several times with the same result, which must be what happened yesterday as well.  In case it was a bad download, I cleared the data in Android so it would download from your servers again, but I get the same result.  So maybe a bad firmware build?

**Comment by Snirpo** [comment]
Ah ok, that means it doesn't boot. And it will fallback to the old version on 5 failed boots. Well, that means this your HU doesn't like this :)

**Comment by Snirpo** [comment]
@luvwot Just built in image where it just reboots the device on connection loss, to force it of the USB bus. Let's see if that makes a difference.

**Comment by luvwot** [comment]
> @luvwot Just built in image where it just reboots the device on connection loss, to force it of the USB bus. Let's see if that makes a difference. You should be able to update now.

OK, installed this one and it boots properly and connects.  I should be able to do a couple short trips in the next few hours to see how it does when my phone goes out of range and the USB remains powered.

**Comment by luvwot** [comment]
> > @luvwot Just built in image where it just reboots the device on connection loss, to force it of the USB bus. Let's see if that makes a difference. You should be able to update now.
> 
> OK, installed this one and it boots properly and connects. I should be able to do a couple short trips in the next few hours to see how it does when my phone goes out of range and the USB remains powered.

@Snirpo Unfortunately this build doesn't improve the situation. With a quick stop to get gas (phone remained in range, about 5 minutes) reconnected just fine. With a longer stop (phone out of range, about 30 minutes) it did not reconnect. Unplugged and re-plugged AAW and it still did not reconnect. USB remained powered the whole time.

**Comment by fg64** [comment]
@Snirpo Uploaded the dev firmware.  Does not appear to function much better than 1.8 did.  First time after uploading the firmware, device connected right away.  Made several stops with mixed results.  Had to remove from projection settings a couple of times to get it working.

**Comment by Snirpo** [comment]
Ok, I'll revert back to the logic of 1.x. I have no explanation for this behavior unfortunately :( I'll try to get a hold of one of these head units.

**Comment by luvwot** [comment]
I don't have an MA1 to test with, and it looks like they're on backorder so I can't even pick one up to help test.

**Comment by Snirpo** [comment]
@luvwot @fg64 created a new build in the connect branch. Trying out some stuff.

**Comment by luvwot** [comment]
> @luvwot Can you possibly contact me on Slack? https://join.slack.com/t/aawireless/shared_invite/zt-1bzbi4tya-9H8rFVCOYKYeyxCvEv_aDQ . I can send an MA1 to you.
> 
> Oh wait... @fg64 might actually be better, because he's in the US. No offence ;)

I'm also in the US (California). I know my HU is reporting as Canada but that's because it's a replacement. (Uconnect only started offering Android Auto in 2018, so I replaced the stock HU in my 2015 with a 2018 model.) I don't believe the replacement/upgrade has anything to do with the unexpected behavior, though.

**Comment by Snirpo** [comment]
@luvwot Aaah, ok, in that cause your HU might be better to test one, cause it seems te behave worse. Can you PM me your address on Slack? (Chiel Prins)

**Comment by sicksixs** [comment]
@Snirpo, went out to the truck at lunch and tried to update.  App is showing "no update available".  Do I need to do anything special to trigger the update?  I tried the regular and the dev app, same results in both.

Also, which app do you want us to help test with?  Thanks.

**Comment by Snirpo** [comment]
Should be active now. You can just use the Play Store version of the app.

**Comment by sicksixs** [comment]
Sorry, still no luck.  I wonder if it's because the device is currently running a dev version: 2.1.0-202206240850-develop-516470d-develop-6803c38f

Do I need to factory reset to get it off the dev firmware first?

**Comment by ajw0** [comment]
Hi @Snirpo, just wanted to add my name to the list of users affected by the this bug. I tried many combinations of passthrough / dongle / USB modes. I actually just received an MA1 device today and initial results are very promising. I'll know for sure after another day or two if it will continue to work. Happy to help test any beta firmware etc.

Name: AAWireless-Ach0XGh6
Firmware: 2.0.2
App: 2.17.0
Vehicle: 2020 Jeep Grand Cherokee

**Comment by Snirpo** [comment]
@sicksixs accidentally enabled the develop branch for you, Uconnect should be enabled now.

**Comment by sicksixs** [comment]
Awesome.  I see the Uconnect version available using the dev app.  Updating now, will let you know how things go.  Thanks for all your support!

**Comment by Snirpo** [comment]
@luvwot Did you already receive the MA1?

**Comment by luvwot** [comment]
> @luvwot Did you already receive the MA1?

Not yet. UPS expects it to be delivered tomorrow (Monday).

**Comment by sicksixs** [comment]
@Snirpo I used the latest Uconnect specific firmware over the weekend, and unfortunately did not see any improvement.  Each time I got in the truck, I had to remove AAwireless from Projection Manager settings, then unplug the device.  I tried leaving the Projection Manager settings alone and just unplugging and plugging back in... no change.  This was on short stops (USB stayed powered on) and long stops.
I tried each USB mode, no difference.
I tried dongle mode on and off, no difference.
I tried passthough mode enabled and disabled, no difference.
Start/stop was enabled the whole time.

2020 Ram 1500 Limited
OnePlus 7 Pro (Android 11)

**Comment by ajw0** [comment]
FWIW I do not have the issue with the MA1. It connects successfully every time I get in the car.

**Comment by luvwot** [comment]
@Snirpo MA1 arrived a little while ago.  I have it connected and will be running some tests today and tomorrow to see how well it reconnects during short (USB powered on) and long (USB powered off) delays.

**Comment by null-character** [comment]
I have this problem also so I am following this thread. Idk if this info helps but when the issue occurs for me the head unit stays in a bad state until it is fully rebooted. It also breaks carplay for my wife's phone as it will connect but no audio will play and it's stuck at zero.

This obviously never happens with the cables only the AAwireless dongle. Not sure what is going on on the headunit side but this is with a Uconnect 4C NAV.

Does 1.12 have the 1.8 USB code or the newer code? If it's the old code please let me know so I can request a downgrade. My unit is the newer revision so I can't go down to 1.8.

**Comment by luvwot** [comment]
@Snirpo Mixed results with the MA1 on a couple short tests.

In the garage, 3-4 tests. USB remained powered on.  MA1 connected properly each time.

Waited 1+ hours, USB powered off. On power-up, MA1 appeared to connect but had no audio (tried Waze, SiriusXM, and Google assistant). Unplugged MA1 and plugged it back in, came on and reconnected.

Three short stops (USB remained powered on), MA1 connected properly each time.

I'm going to let it sit for a couple hours between cycles to see if I can reproduce the no-audio error.

**Comment by Snirpo** [comment]
We'll get one of these HU's, cause debugging this remotely is not really possible. Will keep you up to date.

**Comment by Snirpo** [comment]
@luvwot I'm a bit confused by all these different Uconnect head units. I thought VP3/VP4 were the new ones, but apparently there are different version. I think I need a Mopar built HU? The Harman / Delphi built ones seem the older ones.

**Comment by Brian-Chow** [comment]
> @luvwot I'm a bit confused by all these different Uconnect head units. I thought VP3/VP4 were the new ones, but apparently there are different versions. I think I need a Mopar / Panasonic built HU? The Harman / Delphi built ones seem the older ones.


@Snirpo ,
There are several offered on different trim levels that all run uconnect. There's a basic radio offered on older models and the 'classic' line on Ram pickups, I believe it's a 5". There an 8.4" one, there's an 12" one. The 8.4 and 12 are the Android auto compatible and are used in multiple lines. Prior to 2022, they run uconnect 4, which I believe is QNX based. Uconnect 5 is the latest version shipping on at least the '22 12" version and has wireless Android auto built in, so probably is not a version you want to look at.  I'm having this exact issue and I have a 12" uconnect 4 unit in a 2019 Ram.

**Comment by luvwot** [comment]
@Snirpo You're correct that you need to get a Panasonic-built unit. Those were introduced in 2018 and that's when Android Auto was first available for Uconnect.  The Harman/Delphi units won't have AA.  Prior to 2018 the 8.4" units were VP3; starting in 2018 they moved to VP4. Cosmetically they're extremely similar and are, in fact, plug-compatible.  (In my particular case, my Dodge Durango is a 2015 that came with VP3 and I replaced it with a 2018 VP4 headunit.) Starting in 2019, RAM trucks were offered with a 12" Uconnect while Dodge and Jeep still use the 8.4" units.

@scomoletti I wouldn't expect your 2017 Challenger to have Android Auto support since they didn't add that until 2018.

**Comment by Snirpo** [comment]
@luvwot Ah that got me confused, cause the backend actually says your HU is a VP3. There also seem to be VP2 units with Android Auto / Carplay, but they seem like lower trim levels, like: https://www.ebay.com/itm/294191222381

**Comment by scomoletti** [comment]
The challenger does support android auto, it is a 8.4" 4c unit. I also used to have a '19 jeep cherokee which had the 8.4" 4c in it and while the UI is definitely updated between the two the android auto support was the same. My '22 gladiator also has the same behavior for AA support though again new UI.

**Comment by Brian-Chow** [comment]
This company provides a lot of stereo trim level upgrades to the Mopar community.  It's all OEM equipment, but a selection of radios from the various trims, most of them are going to be uconnect 4c, but I believe they list the uconnect version. https://www.infotainment.com/pages/oem-2013-2020-new-body-style-ram-1500-2500-3500-radios-accessories

**Comment by Snirpo** [comment]
Hmm the 8.4 ones with AA support all seem made by Aptiv, and not vp4, but vp2. Can any one confirm if this is an HU with these issues?

https://www.ebay.com/itm/295087604009?hash=item44b4978129:g:kgcAAOSwhChiyzGX

**Comment by luvwot** [comment]
Mine is definitely an 8.4" from Panasonic
![20200228_202602](https://user-images.githubusercontent.com/106754153/178788102-51fc0d06-b881-47a0-b544-9e07fee11c20.jpg)
![20200228_202628](https://user-images.githubusercontent.com/106754153/178788193-88096518-e5ea-4f2c-84f6-4e9fcdd6caf1.jpg)
![20200228_202539](https://user-images.githubusercontent.com/106754153/178788211-1ddafe58-fa4d-4778-b482-5d164f7bc016.jpg)

**Comment by Snirpo** [comment]
Ah yes I see. https://www.ebay.com/itm/185079185630?hash=item2b179440de:g:rmIAAOSw7hZhVQFo

**Comment by fg64** [comment]
I've been using the last dev Uconnect branch without much luck.  With dongle mode and Passthrough enabled it would on reconnect every other time if that.  With passthough disabled it was hit and miss.  It lasted a couple of days always reconnecting, then one morning it refused to connect.  So far, the dev firmware that was pretty consistent, working 9 or 10 days with no issues, was the from 6/10.

**Comment by Snirpo** [comment]
@sicksixs 
Unfortunately that's not possible for your device because it's a gen2 one. First firmware was 1.12.0.

@fg64 I did not realize that, have to check what was different.

**Comment by fg64** [comment]
@Snirpo If I remember correctly I only had dongle mode enabled.  Start/Stop disabled.

**Comment by luvwot** [comment]
@Snirpo I ran several short and long tests today with the MA1. Every time it did reconnect properly.
Not sure how much this helps.

**Comment by fg64** [comment]
I'll try that.

**Comment by jjansen0013** [comment]
2019 Ram Limited with a galaxy s21 here.

I've had the same issues as the rest. Have any of yall figured out how to see your phone call screen on your phone after placing a call.  Once I hit call, the only way to do anything is on the head unit.

**Comment by null-character** [comment]
> @luvwot Thanks for the confirmation. It's a mystery. I did some USB tracing again today with the MA1 vs AAWireless, and it's bassiccly the same.
> 
> We can probably move back to the logic in 1.8, but it's not really a solution, more of a workaround. And it will only work in normal (non-passthrough) mode.

Hi Snirpo can you please bump me back down to 1.12? My device name is AndroidAuto-AAWNkfNuqOS. Sucks the issue isn't obvious.

**Comment by Snirpo** [comment]
@null-character just did. Please confirm if it works for you.

**Comment by Snirpo** [comment]
Update: @luvwot is going to send the MA1 to @fg64 . One of your devs lives close by @fg64 . We are going to run a USB trace on @fg64 's Dodge RAM.

**Comment by jimbotron123** [comment]
> 

Same here, that's the best I've found. I still have random disconnect issues that plague me pretty often, though I assume I can fix this with a later firmware and the ability to change wifi channels.

**Comment by sicksixs** [comment]
@Snirpo can you drop me down to 1.12 as well?  I remember mine worked pretty well at that time as long as I unplugged it when I left the truck and plugged in when I got back in.  Not ideal, but better than what I have to do currently.  Thanks!

**Comment by sicksixs** [comment]
> @sicksixs he'll need your AA device name. It's in the app like AndroidAuto-XXXXXXXXX.

Yep, I forgot to add that again.  It's in another post earlier in the thread, but I'll copy it here again too.  Thanks.
AAWireless-aTaNRlUX

**Comment by Snirpo** [comment]
@sicksixs Enabled!

**Comment by null-character** [comment]
It's def. working better on 1.12 but start/ stop doesn't seem to work with 1.12 and the new app. Do I need to downgrade the app on the a phone also for start/stop to work? It's a pixel 4a 5g with aawireless set to unrestricted background usage.

**Comment by Snirpo** [comment]
Hmm no start/stop should work with older firmwares as well. But I have to admit we don't really test the app much against older firmwares. Possibly you have to reselect the handsfree device which starts up the bootstrap.

**Comment by sicksixs** [comment]
start/stop working for me on 1.12 so far.  Try disabling, saving, then re-enable and save again.

**Comment by Snirpo** [comment]
Yeah I think for now we revert the 2.0 changes and release 2.1.0. 2.1.0 is hanging on this issue right now. Reverting to to logic of 1.8/1.12 is not really a solution but it's an OK-ish workaround for now.

**Comment by bobcat0070** [comment]
I have the same issues as described above on a 2020 Pacifica Uconnect 4C HU. Is it better to wait for 2.1.0 with reverted logic or request a downgrade to 1.X logic?

AAWireless-kPAUIM2b

**Comment by Snirpo** [comment]
@bobcat0070 I enabled 1.8 for you. We have to test 2.1.0 a bit with the reverted logic, ETA next week.

**Comment by Brian-Chow** [comment]
@Snirpo May I be put back on 1.8 as well? AAWireless-i8Sah50T

**Comment by Snirpo** [comment]
@Brian-Chow 1.12.0 for your device, cause you have a gen2 :) Done.

**Comment by Brian-Chow** [comment]
@Snirpo thank you!  I'm willing to test 2.1.0 as well, if additional people are needed.

**Comment by WGriffing** [comment]
@Snirpo Could you put me back on 1.8/1.12 as well? AAWireless-NP2by4fD

Same issue in a 2020 Jeep Gladiator.

Thanks

**Comment by Snirpo** [comment]
@WGriffing I'm going to blacklist the 2.x firmware for UConnect in the backend for now. 2.x is definitely a big problem for UConnect. You should be able to downgrade this evening when I pushed this change.

**Comment by Brian-Chow** [comment]
@Snirpo just to add confirmation to what others have been reporting -- 1.12 has been working flawlessly for me the past several days.  Using MPT w/ Retry, no passthough, auto connect/disconnect with bluetooth.  This is with a 12" UConnect 4c NAV (UAX)

**Comment by Snirpo** [comment]
@Brian-Chow you probably can use the default MTP mode. Can you try to run with MTP?

**Comment by Brian-Chow** [comment]
@Snirpo Sure, I've got a few errands to run today, I'll switch modes and report back later today.

**Comment by BeavisCH** [comment]
@Snirpo does that mean all uconnect users with aawireless are getting the downgrade automatically or do we need to tell you the device name for you to enable downgrade?
AAWLu3AjZGu

**Comment by Snirpo** [comment]
@BeavisCH Yes, correct. The latest version will be 1.12.0 instead of 2.x.

**Comment by Snirpo** [comment]
@WGriffing @BeavisCH you should be able to downgrade to 1.12.0 now.

**Comment by luvwot** [comment]
> @WGriffing @BeavisCH you should be able to downgrade to 1.12.0 now.

@Snirpo Was that supposed to be for all uconnect users? Mine doesn't show an update option back to 1.12.  If the blacklist for uconnect isn't implemented yet no rush - I can wait.

**Comment by Snirpo** [comment]
@luvwot Only for devices which are still on the default branch, yours was still on the UConnect branch, should be visible now.

**Comment by BeavisCH** [comment]
> @luvwot Only for devices which are still on the default branch, yours was still on the UConnect branch, should be visible now.

Thanks gonna test next week 🤘

**Comment by Brian-Chow** [comment]
> @Brian-Chow you probably can use the default MTP mode. Can you try to run with MTP?

I've had a chance to run MTP mode and it's all been great, 0 issues so far. Connecting and disconnecting seem to work exactly as expected.

**Comment by BeavisCH** [comment]
> @WGriffing @BeavisCH you should be able to downgrade to 1.12.0 now.

Downgraded to 1.12 successfully. In order to get it working I had to remove the device from uconnect projection manager and from aawireless app. After that I reconnected and lal worked fine. 
After letting the car rest over night aawireless didn't reconnect upon entering the car in the morning. 
Gonna try to reset the aaw device and clear all related caches on the phone and set everything up like out of the box. Hope it will work again as usual after that... Will report back.
BR

**Comment by null-character** [comment]
@BeavisCH after downgrading to 1.12 with the new app everything works perfectly so it could work. I have the 8.4" uconnect 4C NAV.

**Comment by WGriffing** [comment]
> @WGriffing @BeavisCH you should be able to downgrade to 1.12.0 now.

I successfully downgraded to 1.12 and AAWireless seems to be back in business. Drove several hours yesterday without any issue. I have passthrough disabled and "MTP with retry" set.

I saw elsewhere in this thread that regular "MTP" should be working, but I haven't tried it yet.

**Comment by Snirpo** [comment]
@WGriffing @BeavisCH @Brian-Chow @null-character @luvwot @fg64 Can you possibly switch to "DEFAULT" USB mode. You might get an error on the HU, but AA should start up anyway. We checked the logs of @fg64 and we have a strong feeling this is where the problem comes from.

**Comment by Brian-Chow** [comment]
@Snirpo I was able to do a small amount of testing with mode set to Default and as expected, it produced an Unsupported Device message on the UConnect screen but works anyways when dismissing the warning.

**Comment by BeavisCH** [comment]
@Snirpo after resetting everything it works as intended with 1.12. Did a few drives today and it connected every time.

**Comment by Snirpo** [comment]
@WGriffing @BeavisCH @Brian-Chow @null-character @luvwot Just realised you're all back on 1.8/12 of course. Still it's good info "DEFAULT" USB mode seems to work ok on 1.8/1.12.

Anyway: I want to try something different. About a month ago we added an experimental "device controlled start / stop". I was reading back some XDA posts and at some point @fg64 was saying it worked it started up fine a few days in a row. It seems like he had this "device controlled start / stop" method enabled. To enable this you need the develop firmware and the dev app: https://appdistribution.firebase.dev/i/210fc06c9667e5f8 

To enable this experimental option, you can go into settings -> start / stop -> device controlled.

I re-enabled the develop firmware for anyone who wants to test.

**Comment by Brian-Chow** [comment]
@Snirpo Do we set Device HFP controlled or Device USB controlled?

**Comment by Snirpo** [comment]
Sorry, USB controlled

**Comment by Brian-Chow** [comment]
@Snirpo minor update. I did the update yesterday, and assumed that HFP was hands free profile (bluetooth) and used USB controlled.  After modifying the settings, it played right away, no need to forget the AAwireless from UConnect.  It started up once from off ok.  Next start from off I had to forget and unplug it, but the start after that it connected without issue or fiddling.  I also don't seem to be getting the Unsupported device message... but it may have also disappeared prior to getting the car -- the past few days it's been pretty hot, so been remote starting for the AC.  I'll report again after I've had a chance to do more on/off connection tests

**Comment by xkraz** [comment]
Great job AAWIRELESS team. I have a 2020 RAM 1500 with 12 inch display. Firmware 1.12.0 works flawless for me now. 
I did have to change my wireless setting from 5g to 2.4g as it would reboot at the same location while on the freeway. 

My current settings:
USB: MTP w/ retry
Passthrough: disabled
WiFi Settings: (Country US, Hotspot, 2.4GHz, channel auto)
Start/Stop: enabled (the 2 experimental options are off)
WiFi Connect Timeout: 20000
VAG crash fix: disabled
Change DPI: 0
Remove tap restriction: disabled
Disable media sink: disabled
Disable TTS sink: disabled
Auto video focus: disabled
Dongle mode: disabled
Developer mode: disabled

**Comment by luvwot** [comment]
Update from a few drives over the last 2-3 days using the latest beta firmware (2.1.0-202207261344-develop-ae2749b-develop-2dc6bdfa) and latest app from Firebase.

A couple short stops (USB remains powered) and a few overnight stops (USB powers off). Everything worked fine through the first part of this morning - a total of 7 or 8 successful connections I think. Then after a short stop I was unable to get AAW to connect (blue blinking LED).  I tried unplugging it and plugging it back in, disconnecting bluetooth on the phone and from the headunit. Unfortunately it won't reconnect. I'm sure that if I have the HU forget the AAW device it will reconnect just fine as it always has.

USB is set to default.
Passthrough is disabled.
Dongle mode is disabled.
I was unable to get the stop/start to work with either of the experimental options so I'm back to using normal Start/Stop mode (bluetooth connection to the HU, I think). When either of the experimental options is enabled I can only connect once (the initial connection). After that, it doesn't work.

@Snirpo I've left it in this state in case there's any test you'd like me to try.

**Comment by Snirpo** [comment]
@luvwot enabled (yet) another branch for you. We copied over some code from Android itself. Can you please try this firmware?

**Comment by Snirpo** [comment]
@luvwot enabled (yet) another branch for you. We copied over some code from Android itself. Can you please try this firmware?

**Comment by Brian-Chow** [comment]
@Snirpo I've had a chance to run the first dev build a while now and had my second instance of having to reboot my unit and forget it from the HU. This seems to be roughly the same behavior that @luvwot experienced as well

**Comment by Snirpo** [comment]
@Brian-Chow We have very promising results from both @luvwot and @fg64 , I'll enable this "dummy-mtp" firmware for you.

**Comment by luvwot** [comment]
The dummy-mtp firmware has been running without a problem. Multiple short trips and long delays, and AAW has connected properly every time.  I think you guys nailed it!

**Comment by fg64** [comment]
Same on my end. 4 days with consistent connects.

**Comment by Brian-Chow** [comment]
Unfortunately, I can't say the same. While it's mostly connected ok, I have had a few issues.

1: my Uconnect crashed and rebooted twice while using AA. I suppose it could be coincidental, but it's never happened before.
2: I've had to forget and unplug/replug just once
3: I had some behavior where AA would start playing music very quickly (good) but then disconnect and auto reconnect.. Sounds like a single disconnect/reconnect cycle length stutter.

**Comment by Snirpo** [comment]
@Brian-Chow Do you have the experimental USB device controlled start/stop enabled? If so, can you disable that option?

**Comment by Brian-Chow** [comment]
@Snirpo  I do have that enables, I'll switch it back and give it a try. I noticed there was a new firmware available, should I upgrade that as well or stay with the MTP-Dummy version?

**Comment by Snirpo** [comment]
Yes, you can upgrade to develop. I merged the changes back to develop. Thanks!

**Comment by xkraz** [comment]
Can you please allow AAwireless-4E9q1gDe to upgrade to dev build?

**Comment by bpsmicro** [comment]
After a few weeks of near-flawless operation, I now need to get in on this action.

AAWireless-j5egnS15
Samsung Galaxy S20 FE 5G
2018 UConnect 8.4"
v1.12.0 firmware (I never upgraded it when I got my AAW because I was reading on XDA there were issues, and not I see "no updates" as expected.

Up to late last week, it worked perfectly probably 90% of the time. The other 10% I might see "Device not Supported" popup, but I could also see Waze running in the background, and clicking OK let me carry on (sometimes the popup went away by itself.

Up to last week, I had two instances where it failed to work at all (just the popup), and in both cases I'd had the vehicle powered for a long time, then walked away (but possibly in WiFi range), then came back.

**One clue though**: on Thursday, my S20FE got the July '22 update (we're usually a month behind in Canada for some reason). And on Friday, deadski. I get nothing by the popup, and AAW totally refuses to work. And, as luck would have it, I was just off on a 3-day road trip *and* the only cables with me sucked (couldn't get wired AA working either other than for brief periods).

I played with various settings, which either made no difference at all (ie USB mode in anything other than Default doesn't connect at all). Passthrough/Dongle/etc (anything I had access to) made either no difference, or just completely did nothing. I "forgot" and re-added the device (though, not on the HU itself, which is something I need to look at next).

I'm still wondering/suspecting if the July '22 Samsung update broke something. That may not be *the* problem, but perhaps relevant.

I'm ready & happy to try any beta builds, since I'm pretty much stuck now anyway. :-)

**Comment by bpsmicro** [comment]
WTF! So after all my poking and prodding, I came inside, typed the above, went back out to see if I could find the place to remove the AAW from the HU, and it all just fired right up as if nothing had happened, It's toying with me now. :-|

**Comment by Brian-Chow** [comment]
@Snirpo I upgraded to 2.1.0-202208090004-dev and it's back to the 2.1x behavior, plus some extra oddities.  I've had to forget and unplug a few times.  It worked flawlessly for a few trips, and for a few trips, I wasn't able to get it to connect at all even with the forget/unplug dance and just gave up.  I also had 2 instances where it would start playing AA and then shortly after music started it crashed out (disconnected) and wouldn't reconnect.

**Comment by Snirpo** [comment]
@Brian-Chow there should be a newer firmware available. But it's to be honest quite confusing. In general this firmware works much better for most. So I'm a bit confused to be honest...

**Comment by Brian-Chow** [comment]
> To confirm, did it ever work 100 percent OK for you? On 1.12.0 for example?

Yes, 1.12 worked perfectly, every time.  

The MTP dummy labeled build worked most of the time, but with some oddball issues like disconnecting and restarting after starting playback.  The 2.1 dev isn't working for me very well at all.  I just got back from another errand and I noticed uconnect reporting unable to find media files for playback when AAWireless wasn't connecting correctly.  I have not tried the latest update.

**Comment by Snirpo** [comment]
@Brian-Chow Can you possibly shoot in some logs, so we can check what the MTP stuff is doing?

**Comment by joeyberkovitz** [comment]
@Brian-Chow - I enabled a firmware for you which reverts some of the newer MTP testing, but pulls in one of the fixes we think is relevant for uConnect. If you can, please test this one and verify if it eliminates that "unable to find media files" error or improves stability.

**Comment by Brian-Chow** [comment]
@Snirpo Is there a way to grab logs prior to clicking on 'Bug report'?  I had enabled (perhaps erroneously)  developer mode before my most recent trip and that happened to be one where it started playing ok, then seemingly crashed, as UConnect quit out of the AA screens and music stopped playing.

@joeyberkovitz Yes, I will update today and let you know how it goes in a few days after I've gotten a few trips in.

**Comment by joeyberkovitz** [comment]
If you send a bug report it'll capture all logs on the device, so no need to wait for another failure

**Comment by Brian-Chow** [comment]
Ok, bug report filed.

**Comment by fgorodishter-godaddy** [comment]
Gotcha. Any suggestions on what the recommended settings would be to run it with Uconnect? Such as USB Mode, Passthrough, Dongle, etc?

**Comment by Snirpo** [comment]
USB mode default or MTP (it's the same thing in 2.1.0), passthrough doesn't really matter, dongle mode also doesn't really matter. Start / stop probably enabled to prevent the the dongle constantly trying to connect to the phone because of the car's USB port staying powered for one hour after turning off the car. However if you have a Samsung phone there's a good chance start/stop won't work well because of horrific battery saving.

**Comment by luvwot** [comment]
@fgorodishter-godaddy I have a Samsung Galaxy S22 and have had good luck using start/stop with the additional "Device USB Controlled" option. It's connected reliably for 2 weeks now and I no longer have the problem of my phone constantly connecting and disconnecting for an hour after I exit the car.

**Comment by Brian-Chow** [comment]
> @Brian-Chow - I enabled a firmware for you which reverts some of the newer MTP testing, but pulls in one of the fixes we think is relevant for uConnect. If you can, please test this one and verify if it eliminates that "unable to find media files" error or improves stability.

It was running fairly well for a while, yesterday I still had an issue where it wouldn't connect.  I needed nav at the time so didn't mess with it too much and just plugged in my phone directly.  I would say.. at least for me.. it's better... but still not as good as 1.12 was.  Should I upgrade to the latest release?  Or factory reset and keep on the dev firmware?  Or combo of both?

**Comment by joeyberkovitz** [comment]
@Brian-Chow - you're back on dev now. It has some small changes to try to improve stability and compatibility over previous dev, so it may be worth a try. If it still doesn't work, please send over a bug report, preferably with at least one connection attempt while the AAW is in debug mode, and we can continue from there.

**Comment by null-character** [comment]
@Snirpo thanks for looking at this and getting it squared away. Can you put me back on stable? AAWNkfNuqOS. I'd like to get on regular 2.1 once it rolls to me.

**Comment by jimbotron123** [comment]
Can you please lift my firmware downgrade restrictions as well please? I have two devices:
AAWireless-282Cm5iE
AndroidAuto-AAWiknizR0o 

Thank you!

**Comment by null-character** [comment]
Hi @Snirpo unfortunately 2.1 has been less stable then 1.12 for me. Can you please downgrade me to 1.12. AAWNkfNuqOS.

Yesterday while driving to work the connection dropped and after reconnecting no AA on the radio. Where even plugging in the phone with a cable wouldn't work. After the car set off for a few hours I went back in and it worked again on my home way from work.

This morning getting in the car it didn't work again, right off the bat. This I think is the first time I have had it not connect when the car was off overnight.

The physical port on my phone is starting to break/get flakey so I need this to work so I don't have to keep plugging it until at least I pay this phone off and can get a new one.

**Comment by bpsmicro** [comment]
@null-character, try this quick-fix and see if it helps. In UConnect, go into the Bluetooth settings, Pairing, Smartphone Projection Manager. Select the AAW and then "Forget" it. Then unplug/replug the AAW and see if it all magically fires up.

My read is that UConnect's knowledge of the AAW device gets confused/corrupted, and once that happens you're in the situation you see until UConnect gets a slap upside the head to forget & remember the AAW again.

Brad.

**Comment by luvwot** [comment]
@Snirpo Still rock-solid on mine. It looks like there's an "official" update now that rolls in the Uconnect fixes. If you want me to test that one, I'm happy to try it.

**Comment by null-character** [comment]
@bpsmicro yeah that usually works but every once in awhile it doesn't.

Also strangely in my Uconnect it showed Nexus listed. I deleted that and after unplugging it and reconnect it showed up as aawireless.

I don't think anything else connected so not sure if Nexus was an incorrectly added aawireless adapter or not.

**Comment by luvwot** [comment]
> @bpsmicro yeah that usually works but every once in awhile it doesn't.
> 
> Also strangely in my Uconnect it showed Nexus listed. I deleted that and after unplugging it and reconnect it showed up as aawireless.
> 
> I don't think anything else connected so not sure if Nexus was an incorrectly added aawireless adapter or not.

I saw Nexus as the initial name of my AAW, too, but after deleting that and adding it back it came up as Uconnect. In a slack conversation, Snirpo told me that's expected.

**Comment by null-character** [comment]
I contacted support to downgrade me to 1.12 since I don't use any of the new features and I was still having some infrequent issues.

I disabled passthrough and I have to do more testing but it seems to be working better.

So this might actually be two issues causing the same or similar problem on the uconnect side.

The issue I was having on passthrough was identical to this one where is says connected but AA never starts.

Removing it from the uconnect and replugging was fixing it same as this issue.

**Comment by Snirpo** [comment]
I'm closing this issue because it's getting way to big. We've been having very little UConnect tickets since 2.1.0, so for most it seems to be fixed. At least, there's no clearing/deleting on the car side necessary anymore. Some car's might need a USB re-plug once in a while, if this is the case please try "MTP with retry" USB mode, because this emulates a re-plug. The MA1 also needs a re-plug once in a while. If it's still not fixed for you, please open a new issue.
