### ISSUE TITLE
Broken TTS

### ISSUE THREAD

**Issue by Thebo84** [cpebit/aawireless-issues#168]
**Describe the bug**
Everything works good audio side, heck thanks to your latest firmware i can even connect now in NON-passthrough mode and change DPI in my Honda civic 2021 FK7. Still whenever TTS is involved (Google Assistant, waze, maps...) audio stutters but it's worst than this.  It starts then sometimes stutters a tiny bit and then interrupts just before finishing. WHenever TTS engine is called in action again it just ends the sentence he had before, even after 20 minutes if the case. Also this creates some concurrent situations when you have to speak the assitant but he has not finished talkin (the beep that signals you have to speak now) and if you wait the final beep it records silence since you had to talk earlier, when he was talking not after the usual beep. If you get what i mean... This creates a neverending loop.

**Screenshots**
NOT applicable

**Device name (AAWireless/AndroidAuto-AAWxxxxxxx) (please complete the following information):**
 - AndroidAuto-AAW993f399b

**Car (please complete the following information):**
 - European Honda Civic Sport+ FK7 2021

**Headunit (please complete the following information):**
 - Original Honda

**Smartphone (please complete the following information):**
 - POCO F2 Pro 8/256
 - Android version 12.1

**Additional context**
The problem happens also with Android 11 on Huawei Note 20 on a different AAwireless device on a Toyota Corolla Hybrid EU 2022. The issue is experienced by others also as you can see in xda thread

Please also create a bug report from the help and support section in the companion app.

**Comment by Thebo84** [comment]
No suggestions? We (everyone I personally know that has AAw) are back to cable since then. Using with this bug is very dangerous while driving it makes you go out of your brain

**Comment by Snirpo** [comment]
The only thing I can suggest is to use passthrough mode. If the same thing happens in passthrough mode (byte per byte straight passthrough), there's nothing we can do at this point. We are aware some cars have this issue (mainly PSA NAC Wave2) and spent alot of time hacking into the AA protocol to fix it. Same thing will happen on any wireless dongle (on NAC2 at least).

**Comment by Thebo84** [comment]
The weird thing at this didn't happened in the first months. Neither to me nor to the people I let buy AAW. Then something happened either android updates, AA updates or AAW updates. Hence why.... I will check once more in passthrough... Btw all the people I know have this issue in Japanese 2021+ cars (honda and Toyota).

I'll report back 

​

Il giorno 26 ott 2022, 07:26, alle ore 07:26, Chiel Prins ***@***.***> ha scritto:

**Comment by Snirpo** [comment]
Hm ok, that's interesting. I enabled 1.12.0 for you for a test.

**Comment by Thebo84** [comment]
is there something boiling here. There was almost no activity on issues since many time. Either is AAWireless project abandoned already or preferably something big is coming for existing users? Hoping for the latter...

**Comment by Snirpo** [comment]
That's because a lot of these issues can not (easily) be solved by us. It's mainly wonkyness in the head unit or Android Auto itself which is amplified by using Android Auto Wireless. We are working on issues, but are mainly communicating directly in Slack with users/testers, because that's much more useful. Feel free to join us at https://join.slack.com/t/aawireless/shared_invite/zt-1n1pdy9hv-dz8VcQW8FK_yPQwENcEqOg

**Comment by Thebo84** [comment]
Issue still massively present. Device Smart assistant functionality are unusable.

**Comment by Thebo84** [comment]
Please do not close the ticket just to clean the tickets queue as it is still unsolved
Also is not possible for me to join you slack account as it request  only
account with the domain:
cpeb.it
radxa.com
