### ISSUE TITLE
Connection drops

### ISSUE THREAD

**Issue by lrigdon** [cpebit/aawireless-issues#97]
I drive a 2021 honda crv exl and use a Samsung galaxy s21+ phone. I was having no issues until I upgraded to version 1.8 and now the dongle seems to restart about every 10-15 minutes. It usually Cycles in under a minute but on one occasion I had to unplug it to get it to connect.  Feel free to contact me as needed 
Lrigdon45@gmail.com 
972-333-8206

**Comment by simonthetall** [comment]
I am having the same issue in a Ford F-150 with a Samsung S21.  My disconnects are more frequent, every couple of minutes or so.  Started with the 1.8 update.

**Comment by Snirpo** [comment]
Hmm hard to say why this happens. We could put you guys back on 1.7.1 for a test?

**Comment by simonthetall** [comment]
That would work for me!  Definitely willing to give that a try.

**Comment by lrigdon** [comment]
I'd like that. I had no problem at all until I upgraded 1.8.  Now I can
hardly make any trip without a reboot of the dongle. Just FYI, I did
encounter a cable issue yesterday and had to replace the cable. It's
connection to the car USB seemed loose.
Thanks,
Lewis Rigdon

**Comment by lrigdon** [comment]
I used the same cable since receiving the dongle with no problems but after
upgrading to 1.8, I experienced frequent reboots of the dongle until it
quit working completely. After some testing, I switched out the cable and
have since only experienced a single reboot. That occurred on the first
outing after the cable change, but none since then. I currently consider
this issue resolved for me.
Lewis Rigdon

**Comment by simonthetall** [comment]
I have tried multiple cables and I still have the reboots.  If I use those same cables and connect my phone directly, I never have any disconnects so my issue is not resolved.

Thanks,

Simon Apperloo
***@***.***
________________________________

**Comment by Snirpo** [comment]
We released 2.0, what are your devices names? I'll enable 2.0.

**Comment by sopelt** [comment]
Hi, I would also like to give 2.0 a try to see if the voice guidance
through the phone might be a workaround for #106 .

Thanks.

E8VsiiOx

Chiel Prins ***@***.***> schrieb am Fr., 29. Apr. 2022, 17:02:

**Comment by Snirpo** [comment]
Done

**Comment by lrigdon** [comment]
Downloaded and installed, I should be able to check it out later this
evening.
Thanks,
Lewis

**Comment by simonthetall** [comment]
Thanks, I will be able to test it this weekend.

**Comment by lrigdon** [comment]
In 30 minutes of driving last evening, after upgrading to version 2.0, I
had one reboot of the dongle so it doesn't look like that has fixed the
issue with random reboots.

**Comment by Snirpo** [comment]
Please try dongle mode as well, we have some reports about this making AA behalve differently for some cars.

**Comment by lrigdon** [comment]
Will do, thanks!

**Comment by pacogeno1** [comment]
Hello: I have updated the Firmware to 2.0.0 on my computer with reference AAWn7IDslmK and when connecting to the Wi-Fi network it asks me for a password, how should I act, thanks

**Comment by lrigdon** [comment]
No improvement in dongle mode. The car's head unit flashes an unsupported
message, drops back to its default mode, the dongle restarts, the car's
android auto mode starts and everything resumes as if nothing happened.

**Comment by Snirpo** [comment]
@lrigdon Very hard to say what the actual problem is. I'm pushing a new version of the app with bug reporting back in. Probably need some logs to see whats happening.

**Comment by lrigdon** [comment]
It seems like the update disabled dongle mode. Leave it off or turn it back
on?

**Comment by pacogeno1** [comment]
Hello: I have updated the Firmware to 2.0.0 on my computer with reference AAWn7IDslmK and when connecting to the Wi-Fi network it asks me for a password, how should I act, thanks

**Comment by Snirpo** [comment]
Debug mode can be enabled from help and support --> bug report in the app.

**Comment by lrigdon** [comment]
Thanks, I'll check it out.

**Comment by lrigdon** [comment]
Did that.  But I'm having an array of issues now. Friday, it quit working
completely. Try as I might, I couldn't get it to connect via bluetooth.
After I reset the dongle, it wouldn't even show up when the phone scanned
for bluetooth devices. I plugged my phone in directly and eventually got
that to work. Back home this morning, I tried it again and after clearing
cache and data, it worked. When I went out later to try it again, it came
up with "Press Android Auto on your car screen". No matter how many times I
press that, nothing happens. It's annoyingly difficult to switch back to
using my phone directly. Previously when I got that message, I had to go
into Android Auto with my phone to clear some messages but that's not the
case this time.

**Comment by simonthetall** [comment]
I have sent in a few logs over the weekend, hope there is something useful in them.

Thanks,

Simon Apperloo
***@***.***
________________________________

**Comment by Snirpo** [comment]
@simonthetall I see two reports from the 6th, will check them out.

@lrigdon What color is the LED after reset? It should be blinking green, in blinking green it's pairable.

**Comment by lrigdon** [comment]
After the reset, it didn't even come on. I was surprised that it paired
this morning but not in the app, I had to go to Bluetooth scan and tried a
couple of times before it actually paired and I was able to return to the
app and continue

**Comment by lrigdon** [comment]
I connected my phone directly and it requested a Bluetooth permission so I
then reconnected the dongle and it worked.
I was able to submit a couple of debug logs of the random dongle restarts.

**Comment by pacogeno1** [comment]
Hello, I have tried the password that you sent me on the Wi-Fi network of my computer with reference "AAWn7IDslmK" and the Wi-Fi network does not connect me, there must have been an error in the password, could you confirm it again .. please Thank you

**Comment by pacogeno1** [comment]
Hello, when I try to connect to the Wi-Fi network it asks me for a Wi-Fi password,,, my equipment with reference "AAWn7IDslmK" and I cannot connect to the Wi-Fi network, could you confirm the password, please, thanks

**Comment by simonthetall** [comment]
Chiel,
How many bug reports do you need from us?  I see the app has been getting some updates, so I have been watching that carefully to see if there are more resets.

Simon

**Comment by Snirpo** [comment]
We'll spend some time next week to investigate connection dropping. It's really really hard to debug, cause it's not a high level software issue. Could be anything bassiccly.

**Comment by lrigdon** [comment]
Updated to 2.0.1, still getting random restarts. It's strange because it
can go for a few days without a problem then multiple times in a single
short trip

**Comment by gtavo** [comment]
I'm experiencing also random restarts or connections lost, (Ford Focus 2019), it happens more often in places with poor reception (underground parking, mountain roads...)

**Comment by Snirpo** [comment]
@Irigdon

If this problem only happens in non-passthrough, it should be fixed in 2.0.2.

@gtavo

If you have an Xiaomi phone the problem is: #102

**Comment by EVPower2k13** [comment]
I Installed the lastest firmware 2.0.2 but the dropout is still occuring. Samsung S10e with Kona Electric. Mostly on short trip. I always listening to youtube in car and the audio drop for 1-2 sec then continue. But at the second and 3rd time, the led is solid white. Only way, to make it works again, is to unplug and replug. 

What do you need to debug it further.

Thanks.

**Comment by tallLeRoy** [comment]
Here are the settings I use on my Samsung S20 FE 5G with no problems. 

I do not use a VPN.

Settings->Connections->Wi-Fi:::Advanced: Sync with Samsung Cloud - Disabled
Settings->Connections->Wi-Fi:::Advanced: Switch to mobile date - Enabled
Settings->Connections->Wi-Fi:::Advanced: Turn on Wi-Fi automatically - Disabled
Settings->Connections->Wi-Fi:::Advanced: Show network quality info - Enabled
Settings->Connections->Wi-Fi:::Advanced: Network Notification - Disabled
Settings->Connections->Wi-Fi:::Advanced: Hotspot 2.0 - Disabled

Settings->Connections->Mobile Hotspot and Tethering: Moble Hotspot - Disabled
Settings->Connections->Mobile Hotspot and Tethering: Bluetooth tethering - Disabled
Settings->Connections->More connection settings: Nearby device scanning - Disabled

Settings->Advanced features->Android Auto: All sliders Enabled

Settings->Battery and device care->Battery: Power saving - Disabled
Settings->Battery and device care->Battery->Background usage limits: Put unused apps to sleep - Enabled
Settings->Battery and device care->Battery->Background usage limits: Never sleeping apps - Only Gmail on the list
Settings->Battery and device care->Battery->More battery settings: Protect battery - Disabled
Settings->Battery and device care->Battery->More battery settings: the rest are Enabled

I hope this can be of help to those with Samsung phones. I have a bit of empathy for @simonthetall, we share a common trait. 

LeRoy

**Comment by lrigdon** [comment]
I'm still seeing occasional unexpected restarts of the dongle, but it
recovers fairly quickly and is less frequent than with 2.0.  I'm currently
using 2.0.2 and although annoying, I don't consider it a major issue,
unlike when I first upgraded to 2.0. Although it's interesting that the
release prior to 2.0 experienced none of these issues.

Lewis

**Comment by Snirpo** [comment]
Closing this issue because of no activity. If the problem persists, please create a new issue.

**Comment by lrigdon** [comment]
It still happens occasionally, but with the latest version, it recovers
quicker. It's not enough of an issue for me to mess with.

Lewis Rigdon

**Comment by simonthetall** [comment]
Mine when away once I received an update for Android Auto and the July update from Samsung.  Sorry that I didn't advise.

**Comment by lrigdon** [comment]
What do we need to do to roll back to 1.7.1?
Thanks,
Lewis

**Comment by simonthetall** [comment]
So I tested 2.0 over the weekend.  I am still getting resets with and without Dongle mode.  It might actually be a bit worse in Dongle mode  for frequency of resets.

**Comment by lrigdon** [comment]
Not sure what has changed, but after Monday the 9th when I submitted two
logs, I have experienced only 1 unexpected restart of the dongle. That's a
significant reduction. If the incidence goes up again, I will again submit
logs.
Of course, on that Monday, I had done a reset of the dongle, cleared cache
for AA Wireless and Android Auto, directly connected my phone and cleared a
couple of Android Auto notifications, so no telling if any of that helped.

Lewis Rigdon
